version: '3'

services:

  # Host===================================================================
  nginx:
    image: nginx:1.12
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./app/:/var/www/html/
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx/

  # App===================================================================
  app:
    container_name: app
    build: docker/app
    volumes:
      - ./app/:/var/www/html/
      - ./docker/app/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini

  # NPM===================================================================
  node:
    image: node:lts
    container_name: node
    volumes:
      - ./app/:/var/www/html/
    working_dir: /var/www/html/
    entrypoint: [ "npm" ]
    command: [ "--help" ]

  # Database===================================================================
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db:
    driver: local
